### PR TITLE
Include list of available modules

### LINKED ISSUE #1: Please include list of available includes in cdn main page
Please put a list of files we can use from https://github.com/opal/opal-cdn/tree/gh-pages/opal/current at http://cdn.opalrb.org/.

### PR DESCRIPTION
**Pull request by ggrossetie**
Resolves #1

Result:

new_index_cdn_page

### CODE REVIEW

**Comment by ggrossetie** [comment]
@elia @ylluminarious what do you think ?

**Comment by elia** [comment]
Nice!

(As time permits would be cool to scope them by version and maybe attach links the various versions to each file.)

**Comment by ylluminarious** [comment]
@Mogztter Yeah, thanks, this looks better. It's nice not having to go here on GitHub to see what's available on Opal's CDN :grinning:.

**Comment by ggrossetie** [comment]
> As time permits would be cool to scope them by version and maybe attach links the various versions to each file.

That's a good idea and maybe we can use the GitHub API to [get contents of a directory](https://github.com/k33g/gh3#get-contents-of-a-directory). That way we don't need to edit the index page for each new release.

@elia Currently the page is using Opal to generate the content but I think it would be better to just use a plain HTML page. That will allow us to use CSS and JavaScript to create a beautiful index page. Is that OK for you ?

**Comment by elia** [comment]
Yeah it was just a way to show off the CDN itself but has no real value. 

As an alternative to the github API an index page could be generated as part of the "dist" task. And the main index page link to each sub-index.

**Pull request merged**
