### PR TITLE
Regenerate opal.js in 0.7.1 with correct RUBY_ENGINE_VERSION

### PR DESCRIPTION
**Pull request by supermario**
After much head scratching at why the current [0.7.1/opal.min.js](http://cdn.opalrb.org/opal/0.7.1/opal.min.js) on the CDN is reporting itself to be `0.6.1` – I figured out that the `RUBY_ENGINE_VERSION` wasn't updated when [opal was bumped to 0.7.1](https://github.com/opal/opal/commit/a1dffdb68f5017e31741641698a6139b6da949c1).

I figure not much we can do about the tag, but at least we can fix the CDN copy? :smiley: 

@Mogztter FYI!

### CODE REVIEW

**Comment by elia** [comment]
I think the best way would be to release 0.7.2 wdyt?

**Comment by supermario** [comment]
Makes sense to me!

**Comment by elia** [comment]
would you mind sending a PR on opal/opal with that fix?

**Comment by elia** [comment]
of course it should target branch https://github.com/opal/opal/tree/0-7-stable

**Comment by supermario** [comment]
On it.

**Comment by supermario** [comment]
Closing in favor of new build for 0.7.2. Thanks!

**Pull request closed without merging**
