### PR TITLE
Add 0.11.4

### LINKED ISSUE #29: v0.11.4 for opal-cdn
Hi, developers!

Opal v0.11.4 has been released: https://github.com/opal/opal/releases/tag/v0.11.4.
Do you have a plan to release opal-cdn for v0.11.4?

I was wondering if you could tell me how to build `opal.min.js` or `opal-parser.min.js` by my own from [opal/opal](https://github.com/opal/opal).

### PR DESCRIPTION
**Pull request by nwtgck**
Hi, developers!

I made PR to resolve #29.
I just added `opal-cdn/opal/0.11.4` and updated `opal-cdn/opal/current`. I did not update  `opal-cdn/opal/master`.

### CODE REVIEW

**Comment by nwtgck** [comment]
Sorry. I found the wrong build. I built `0.11.99.dev`.  So I'll checkout `v0.11.4`.

**Comment by nwtgck** [comment]
The problem below was solved when I used Ruby 2.5.1
- - - 

~~In the latest master, `rake dist` was successful.~~
~~latest master: https://github.com/opal/opal/commit/6703d8d274b38b9e9e8bc6988f277e189a729048~~

~~However, In [`v0.11.4`](https://github.com/opal/opal/tree/9b19e21020b5f5d8ccf57896afe31483e20e6188), `rake dist` was failed with~~


~~Could not find gem 'mspec' in source at `spec/mspec`.~~  
~~The source does not contain any versions of 'mspec'~~

**Comment by nwtgck** [comment]
I just added and updated
* `opal-cdn/opal/0.11.4`
* `opal-cdn/opal/current`

But I did not update `opal-cdn/opal/master`.

**Comment by elia** [comment]
Fixed by https://github.com/opal/opal-cdn/commit/055dc2f933271a8ea27ab3b3ee1d393112cda769 
I ended up launching the scripts locally, was easier than using the PR, but thanks very much anyway, it's always great to get contributions!!! 👍👍👍

**Pull request closed without merging**
